Add missing include - stdio.h
Fixes build error:

g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT unixoutstreambuf.o -MD -MP -MF .deps/unixoutstreambuf.Tpo -c -o unixoutstreambuf.o `test -f 'io/unixoutstreambuf.cpp'   || echo './'`io/unixoutstreambuf.cpp
io/unixoutstreambuf.cpp: In member function ‘virtual int IO::UnixOutStreambuf::overflow(int)’:
io/unixoutstreambuf.cpp:61:20: error: ‘EOF’ was not declared in this scope
make[3]: *** [unixoutstreambuf.o] Error 1
make[3]: Leaving directory `realtimebattle/rtb-team-framework'
make[2]: *** [all] Error 2
make[2]: Leaving directory `realtimebattle/rtb-team-framework'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `realtimebattle'
make: *** [all] Error 2